# Generated by Django 3.1.3 on 2020-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('trial_start_date', models.CharField(max_length=50)),
            ],
        ),
    ]
