# Generated by Django 3.1.3 on 2020-12-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pseudoID', models.CharField(max_length=20)),
                ('deviceInformation', models.CharField(max_length=2000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
